CREATE DATABASE postickdb;
USE postickdb;

CREATE TABLE IF NOT EXISTS `posticks`(
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(50) COLLATE utf8_unicode_ci NOT NULL,
    `description` VARCHAR(200) COLLATE utf8_unicode_ci NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

DESCRIBE posticks;
